#!/bin/bash
# Add tracked modified files (excluding build artifacts) and commit (no push)

git ls-files --modified | grep -vi -e 'Prebuild.bat' -e 'ZigbeeStack' \
    -e 'ZigbeeAppCommon' -e 'SecureEFR32Bootloader' -e 'BuildAll.bat' -e 'cFMT.h' \
    | tr -d '\r' | xargs -d '\n' git add
git commit -m "$*"
